version: "3.7"

services:
  zookeeper:
    image: quay.io/debezium/zookeeper:1.9
    restart: always
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - debezium

  kafka:
    image: quay.io/debezium/kafka:1.9
    restart: always
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - ADVERTISED_HOST_NAME=10.211.55.7
    networks:
      - debezium

  kafka-manager:
    container_name: kafka-manager
    restart: always
    image: obsidiandynamics/kafdrop:latest
    ports:
      - 9000:9000
    environment:
      #- JVM_OPTS="-Xms32M -Xmx64M"
      - KAFKA_BROKERCONNECT=kafka:9092
    links:
      - kafka
    networks:
      - debezium

  # mysql:
  #   image: quay.io/debezium/example-mysql:1.9
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=debezium
  #     - MYSQL_USER=mysqluser
  #     - MYSQL_PASSWORD=mysqlpw
  #   networks:
  #     - debezium

  connect:
    image: quay.io/debezium/connect:1.9
    restart: always
    ports:
      - 8083:8083
    links:
      - kafka
      - mysql
    environment:
      - BOOTSTRAP_SERVERS=10.211.55.7:9092
      - GROUP_ID=dbtransfer
      - CONFIG_STORAGE_TOPIC=dbtransfer_configs
      - OFFSET_STORAGE_TOPIC=dbtransfer_offsets
      - STATUS_STORAGE_TOPIC=dbtransfer_statuses
    networks:
      - debezium
  # debezium-ui:
  #   image: quay.io/debezium/debezium-ui:1.9
  #   ports:
  #     - 8080:8080
  #   links:
  #     - connect
  #   environment:
  #     - KAFKA_CONNECT_URIS=kafka:9092
  #   networks:
  #     - debezium

  debezium-client:
    restart: always
    build:
      context: .
    links:
      - connect
    command:
      - "-c=etc/config.yaml"

networks:
  debezium:
    name: debezium
    driver: bridge
