version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch
    environment:
      - node.name=es0
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - discovery.type=single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "9200:9200"
      - "9300:9300"
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:latest
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
     - 8080:8080
    environment:
     - SERVER_ID=1
     - SERVER_COUNT=1
  kafka:
    container_name: kafka
    image: debezium/kafka:latest
    ports:
     - 9092:9092
    environment:
     - ZOOKEEPER_CONNECT=192.168.50.199:2181
     - HOST_NAME=0.0.0.0
     - ADVERTISED_HOST_NAME=192.168.50.199
     - BROKER_ID=1
  postgres:
    container_name: postgres
    image: debezium/example-postgres:latest
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
  connect:
    container_name: debeconn
    image: debezium/connect:latest
    ports:
     - 8083:8083
    environment:
     - BOOTSTRAP_SERVERS=192.168.50.199:9092
     - GROUP_ID=example.inventory
     - CONFIG_STORAGE_TOPIC=example_inventory_configs
     - OFFSET_STORAGE_TOPIC=example_inventory_offsets
     - STATUS_STORAGE_TOPIC=example_inventory_statuses
volumes:
  esdata: